### ISSUE TITLE
Broken Animation

### ISSUE THREAD

**Issue by yarodevuci** [ed-asriyan/lottie-converter#96] opened 2024-08-20 05:19 UTC
[TwisterDog_AgADWgADTlzSKQ.tgs.zip](https://github.com/user-attachments/files/16669339/TwisterDog_AgADWgADTlzSKQ.tgs.zip)

Broken animation for this sticker

**Comment by ed-asriyan** [comment] 2024-09-04 00:27
I didn't find any errors or incorrect conversion for any of the supported formats. Could you please specify which command you use and a screenshot of what you expect to get after conversion?

**Comment by yarodevuci** [comment] 2024-09-04 00:42
there is no errors, @ed-asriyan just the animation is wrong

**Comment by ed-asriyan** [comment] 2024-09-04 00:50
could you provide a screenshot of the converted animation that demonstrates the defect, and provide command you used to convert the animation?

**Comment by yarodevuci** [comment] 2024-09-04 00:53
yes, working on it

**Comment by yarodevuci** [comment] 2024-09-04 00:55
`docker run --rm -e HEIGHT=256 -e WIDTH=256 -e QUALITY=100 -v /FunkyGoose:/source edasriyan/lottie-to-gif`

**Comment by yarodevuci** [comment] 2024-09-04 00:56
![FunkyGoose_AgADRgADUomRIw tgs](https://github.com/user-attachments/assets/4f8e6d47-97e3-4bac-8bec-78760264f6a0)
here is another example

**Comment by yarodevuci** [comment] 2024-09-04 01:00
![TwisterDog_AgADWgADTlzSKQ tgs](https://github.com/user-attachments/assets/21c0c0d8-ff81-42c0-8e37-45ef82b11858)
do you see artifact on top ?

**Comment by yarodevuci** [comment] 2024-09-04 01:01
not sure if you are able to improve such behavior

**Comment by ed-asriyan** [comment] 2024-09-04 01:35
> ![FunkyGoose_AgADRgADUomRIw tgs](https://private-user-images.githubusercontent.com/13408859/364187659-4f8e6d47-97e3-4bac-8bec-78760264f6a0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTM3OTgsIm5iZiI6MTcyNTQxMzQ5OCwicGF0aCI6Ii8xMzQwODg1OS8zNjQxODc2NTktNGY4ZTZkNDctOTdlMy00YmFjLThiZWMtNzg3NjAyNjRmNmEwLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAxMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZDEwZWJiYWM0NGM1NGRmMmJmYzEwZGRmOGU5OTMyODc5NmMzZWZmNDI3ZmZmZjk2MTYzOWFmZmFkYjk0ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VmE6E4XChNdpUY_w3m5Eibp6BgO55PtYQerk9K-cKCA)
> here is another example Artifacts on screen reflections

this is how "transparency" is imitated in non-transparent GIFs. this is expected behavior


> ![TwisterDog_AgADWgADTlzSKQ tgs](https://private-user-images.githubusercontent.com/13408859/364188304-21c0c0d8-ff81-42c0-8e37-45ef82b11858.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU0MTM3OTgsIm5iZiI6MTcyNTQxMzQ5OCwicGF0aCI6Ii8xMzQwODg1OS8zNjQxODgzMDQtMjFjMGMwZDgtZmY4MS00MmMwLThlMzctNDVlZjgyYjExODU4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA0VDAxMzEzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMzIxYWU2NjhkYWQ1ZTQxYTQwYTVhOGYwMDIzMzYyZjg2MDVmZjc5NzNkNzIzZTFkNTM1NTYyOGU5OGU0NWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._9WDqIj09IcLOmcWe1WRctQqXLBAv9D7ibx2q1V0hqY)
> do you see artifact on top ?

hmm, it seems to be gifski bug which is fixed in the latest version. please wait for a fix with upgraded gifski inside

**Closed** 2024-09-04 01:40 UTC
Labels: bug

**Comment by yarodevuci** [comment] 2024-09-04 02:10
@ed-asriyan Thanks! will my docker automatically picks up the update? How do i know when it's ready?

**Comment by ed-asriyan** [comment] 2024-09-04 02:12
it will be available in a few minutes. I'll let you know

**Comment by yarodevuci** [comment] 2024-09-04 03:20
@ed-asriyan I just pulled the latest, artifact issue on balloon dog is gone, but goose monitor reflection is not :( 
many other animated stickers have that similar issue too. Any ideas what that could be and how to get rid of it?

**Comment by yarodevuci** [comment] 2024-09-04 03:21
![FunkyGoose_AgADoRgAApWxgUg tgs](https://github.com/user-attachments/assets/812e8c62-b21c-4c48-98f6-1c5f6a979a53)
here is another example

**Comment by yarodevuci** [comment] 2024-09-04 03:21
I think most premium stickers have these in common

**Comment by ed-asriyan** [comment] 2024-09-04 03:39
these “shadows” are partially transparent. GIF does not support alpha channel (transparent), so you see these rare dots simulating transparency. for better quality, choose other formats that support alpha channel, such as apng, webp, or webm

**Comment by yarodevuci** [comment] 2024-09-04 03:42
> these “shadows” are partially transparent. GIF does not support alpha channel (transparent), so you see these rare dots simulating transparency. for better quality, choose other formats that support alpha channel, such as apng, webp, or webm

hm, and then convert any of those formats to gif?

**Comment by yarodevuci** [comment] 2024-09-04 03:43
possible to add webp or webm to gif?

**Comment by yarodevuci** [comment] 2024-09-04 03:47
most of the webp animation is broken ;((

**Comment by ed-asriyan** [comment] 2024-09-04 03:55
> hm, and then convert any of those formats to gif?
no. gif doesn't have support of alpha channel so information about transparency "level" is lost in gif regardless what it was converted from

> possible to add webp or webm to gif?
no they are different formats. try to use [these commands](https://github.com/ed-asriyan/lottie-converter?tab=readme-ov-file#using-docker)

> most of the webp animation is broken/wrong loop speed ;((
it's expected. absolute value of FPS may vary slightly on different formats, as different formats use different ways of defining “speed”: some use FPS, others use “frame duration”. could you give examples where you've had this problem?

**Comment by yarodevuci** [comment] 2024-09-04 04:09
Yea, unfortunately apng is no go for me, since size for it is huge, 2.5+3+ MB, compared to GIF 1MB, webm also won't work for me on iOS devices. 

I can't attached WebP but I am attaching tgs zip file instead that you can run tests with...

[TGSFiles.zip](https://github.com/user-attachments/files/16860678/TGSFiles.zip)

**Comment by ed-asriyan** [comment] 2024-09-04 04:20
I converted the files to webp and opened them in Chrome. I don't see any ripped out chunks of image frames. As expected, there is a slight difference in FPS that can be seen after a few cycles. Could you please clarify exactly what you see, or attach a zip file of the webp files?

**Comment by yarodevuci** [comment] 2024-09-04 04:41
> I converted the files to webp and opened them in Chrome. I don't see any ripped out chunks of image frames. As expected, there is a slight difference in FPS that can be seen after a few animation cycles. Could you please clarify exactly what you see, or attach a zip file of the webp files?

You are correct, on the Mac Preview app they look broken, but in Chrome they look fine, either way I tried on iOS and animations is similarly broken there as well.. I guess it depends on the preprocessor that is been used.

Possible to code partial transparency to be fully transparent instead? I have seen Telegram bot does that actually.

**Comment by yarodevuci** [comment] 2024-09-05 04:24
![TwisterDog_AgADWQADTlzSKQ tgs](https://github.com/user-attachments/assets/091caff3-4715-437b-88c0-39a02e0928e6)
![TwisterDog_AgADWwADTlzSKQ tgs](https://github.com/user-attachments/assets/5ee8a2bf-c11e-4afb-ba79-c97c6f8fd2f6)
few animations are still broken unfortunately ... @ed-asriyan

**Comment by yarodevuci** [comment] 2024-09-05 04:25
![1](https://github.com/user-attachments/assets/84df6285-8a3a-4ef5-b991-f9148c04c09f)
![TwisterDog_AgADWwADTlzSKQ-ezgif com-resize](https://github.com/user-attachments/assets/8abfc7fd-01f3-4c33-a51a-5ac2ce076fd5)
Here are they should be

**Comment by ed-asriyan** [comment] 2024-09-06 00:56
> Possible to code partial transparency to be fully transparent instead? I have seen Telegram bot does that actuall

Technically it's possible and looks like an enhancement. Here is an issue to make in in future: #98

> few animations are still broken unfortunately ... @ed-asriyan

could you please send animations here or provide a link to the stickers?

>  Here are they should be

how did you generate these gifs?

**Comment by yarodevuci** [comment] 2024-09-06 05:38
[TwisterDog.tgs.zip](https://github.com/user-attachments/files/16903292/TwisterDog.tgs.zip)
@ed-asriyan here is the zip
docker run --rm -e HEIGHT=256 -e WIDTH=256 -e QUALITY=60 -v /Users/yaro/Downloads/VoiceChanger/Twister:/source edasriyan/lottie-to-gif

I appreciate a lot your time to check this.

**Comment by yarodevuci** [comment] 2024-09-11 07:30
@ed-asriyan hi there, any updates on this?

**Comment by ed-asriyan** [comment] 2024-09-11 23:23
not yet. I'll take a look later when will have free time. Most likely in a few weeks

**Comment by yarodevuci** [comment] 2024-10-08 19:15
@ed-asriyan have you had a chance to take a look?
